
package com.capgemini.adegParalleloService.client;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.7-b01-
 * Generated source version: 2.1
 * 
 */
@WebFault(name = "Fault", targetNamespace = "http://www.accenture.com/ADEG0/WSADEG1/")
public class WSADEG1Fault
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private NBPErrorInfoType faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public WSADEG1Fault(String message, NBPErrorInfoType faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public WSADEG1Fault(String message, NBPErrorInfoType faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: com.capgemini.adegParalleloService.client.NBPErrorInfoType
     */
    public NBPErrorInfoType getFaultInfo() {
        return faultInfo;
    }

}
