
package com.capgemini.adegParalleloService.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.7-b01-
 * Generated source version: 2.1
 * 
 */
@WebService(name = "WSADEG1", targetNamespace = "http://www.accenture.com/ADEG0/WSADEG1/")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WSADEG1 {


    /**
     * 
     * @param parameter
     * @param header
     * @return
     *     returns com.capgemini.adegParalleloService.client.WSADEG1ResponseType
     * @throws WSADEG1Fault
     */
    @WebMethod(operationName = "WSADEG1", action = "http://www.accenture.com/ADEG0/WSADEG1/")
    @WebResult(name = "WSADEG1Response", targetNamespace = "http://www.accenture.com/ADEG0/WSADEG1/", partName = "parameters")
    public WSADEG1ResponseType wsadeg1(
        @WebParam(name = "ISPWebservicesHeader", targetNamespace = "http://intesasanpaolo.it/", header = true, partName = "header")
        ISPWebservicesHeaderType header,
        @WebParam(name = "WSADEG1Request", targetNamespace = "http://www.accenture.com/ADEG0/WSADEG1/", partName = "parameter")
        WSADEG1RequestType parameter)
        throws WSADEG1Fault
    ;

}
