<?xml version="1.0" encoding="UTF-8"?>
<!--File Interfaces/ADEG0_WSADEG1.wsdl, application WSADEG1_ADEG0_CS_WSADEG1, static library WSADEG1_ADEG0_MM_WSADEG1-->
<wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:intns="http://intesasanpaolo.it/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="http://www.accenture.com/ADEG0/WSADEG1/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsd1="http://ws.intesasanpaolo.com/" xmlns:xsd2="http://www.accenture.com/ADEG0/WSADEG1/" name="WSADEG1" targetNamespace="http://www.accenture.com/ADEG0/WSADEG1/">
	<wsdl:documentation>
		<wsdl:appinfo source="WMQI_APPINFO">
			<MRWSDLAppInfo imported="true">
				<generatedXSD location="Interfaces/ADEG0_WSADEG1_InlineSchema.xsd" />
				<binding hasEncoding="false" imported="true" name="WSADEG1SOAP" originalBindingStyle="document" />
			</MRWSDLAppInfo>
		</wsdl:appinfo>
	</wsdl:documentation>
	<wsdl:types>
		<xsd:schema xmlns:ibmSchExtn="http://www.ibm.com/schema/extensions" targetNamespace="http://www.accenture.com/ADEG0/WSADEG1/">
			<xsd:import namespace="http://intesasanpaolo.it/" schemaLocation="WSADEG1_0.xsd" />
			<xsd:include schemaLocation="WSADEG1_1.xsd" />
		</xsd:schema>
		<xsd:schema>
			<xsd:import namespace="http://www.accenture.com/ADEG0/WSADEG1/" schemaLocation="WSADEG1_1.xsd" />
		</xsd:schema>
		<xsd:schema targetNamespace="http://www.accenture.com/ADEG0/WSADEG1/" />
	</wsdl:types>
	<wsdl:message name="WSADEG1Request">
		<wsdl:part element="intns:ISPWebservicesHeader" name="header" />
		<wsdl:part element="tns:WSADEG1Request" name="parameter" />
	</wsdl:message>
	<wsdl:message name="WSADEG1Response">
		<wsdl:part element="tns:WSADEG1Response" name="parameters" />
	</wsdl:message>
	<wsdl:message name="WSADEG1Fault">
		<wsdl:part element="tns:Fault" name="error" />
	</wsdl:message>
	<wsdl:portType name="WSADEG1">
		<wsdl:operation name="WSADEG1">
			<wsdl:input message="tns:WSADEG1Request" />
			<wsdl:output message="tns:WSADEG1Response" />
			<wsdl:fault message="tns:WSADEG1Fault" name="fault" />
		</wsdl:operation>
	</wsdl:portType>
	<wsdl:binding name="WSADEG1SOAP" type="tns:WSADEG1">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http" />
		<wsdl:operation name="WSADEG1">
			<soap:operation soapAction="http://www.accenture.com/ADEG0/WSADEG1/" />
			<wsdl:input>
				<soap:header message="tns:WSADEG1Request" part="header" use="literal" />
				<soap:body parts="parameter" use="literal" />
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal" />
			</wsdl:output>
			<wsdl:fault name="fault">
				<soap:fault name="fault" use="literal" />
			</wsdl:fault>
		</wsdl:operation>
	</wsdl:binding>
	<wsdl:service name="WSADEG1">
		<wsdl:port binding="tns:WSADEG1SOAP" name="WSADEG1SOAP">
			<soap:address location="http://salcls0295.sede.corp.sanpaoloimi.com:7834/ADEG0/WSADEG1" />
		</wsdl:port>
	</wsdl:service>
</wsdl:definitions>
